// src/App.vue
<script setup lang="ts">
import { h, ref } from "vue";
import DownloadView from "./DownloadView.vue";
import RecognizerView from "./RecognizerView.vue";
import HistoryView from "./HistoryView.vue";
import {
  DownloadOutlined,
  AudioOutlined,
  HistoryOutlined,
} from "@ant-design/icons-vue";

type ViewKey = "download" | "recognize" | "history";
const active = ref<ViewKey>("download");
// 音频识别子菜单展开状态（受控）
const openKeys = ref<string[]>([]);

// antd Menu 的 items：音频识别作为父项，下挂「识别」「历史记录」两个子项
const items = [
  {
    key: "download",
    icon: h(DownloadOutlined),
    label: "B站下载",
  },
  {
    key: "recognize-group",
    icon: h(AudioOutlined),
    label: "音频识别",
    children: [
      { key: "recognize", icon: h(AudioOutlined), label: "识别" },
      { key: "history", icon: h(HistoryOutlined), label: "历史记录" },
    ],
  },
];

function onMenuClick({ key }: { key: string }) {
  // 仅子项（无 children）才切换主视图
  if (key === "recognize" || key === "history" || key === "download") {
    active.value = key as ViewKey;
  }
}

function onOpenChange(keys: string[]) {
  openKeys.value = keys;
}
</script>

<template>
  <a-layout class="layout">
    <a-layout-sider :width="220" theme="dark" class="sider">
      <div class="brand">
        <span class="logo">♪</span>
        <span class="brand-name">Audio Processor</span>
      </div>
      <a-menu
        :selectedKeys="[active]"
        :openKeys="openKeys"
        theme="dark"
        mode="inline"
        :items="items"
        @click="onMenuClick"
        @openChange="onOpenChange"
      />
    </a-layout-sider>

    <a-layout-content class="content">
      <download-view v-if="active === 'download'" />
      <recognizer-view v-else-if="active === 'recognize'" />
      <history-view v-else-if="active === 'history'" />
    </a-layout-content>
  </a-layout>
</template>

<style scoped>
.layout {
  height: 100vh;
  width: 100vw;
}
.sider {
  overflow: auto;
}
.brand {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  height: 64px;
  padding: 0 1.2rem;
  font-size: 1.05rem;
  font-weight: 700;
  color: #fff;
  border-bottom: 1px solid #303030;
}
.logo {
  color: #38bdf8;
  font-size: 1.3rem;
}
.content {
  background: #f5f7fa;
  overflow: hidden;
}
</style>

// src/App.svelte
<script lang="ts">
  import DownloadView from './DownloadView.svelte';
  import RecognizerView from './RecognizerView.svelte';

  // 当前选中的菜单项：download | recognize
  let active = $state<'download' | 'recognize'>('download');
</script>

<div class="layout">
  <aside class="sidebar">
    <div class="brand">
      <span class="logo">♪</span>
      <span class="brand-name">Audio Processor</span>
    </div>
    <nav>
      <button
        class="nav-item"
        class:active={active === 'download'}
        onclick={() => (active = 'download')}
      >
        <span class="nav-icon">⬇</span> B站下载
      </button>
      <button
        class="nav-item"
        class:active={active === 'recognize'}
        onclick={() => (active = 'recognize')}
      >
        <span class="nav-icon">🔍</span> 音频识别
      </button>
    </nav>
  </aside>

  <main class="content">
    {#if active === 'download'}
      <DownloadView />
    {:else}
      <RecognizerView />
    {/if}
  </main>
</div>

<style>
  .layout {
    display: flex;
    height: 100vh;
    width: 100vw;
  }
  .sidebar {
    width: 220px;
    flex-shrink: 0;
    background: #1f2937;
    color: #e5e7eb;
    display: flex;
    flex-direction: column;
    padding: 1rem 0;
  }
  .brand {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0 1.2rem 1rem;
    font-size: 1.05rem;
    font-weight: 700;
    border-bottom: 1px solid #374151;
    margin-bottom: 0.5rem;
  }
  .logo {
    color: #38bdf8;
    font-size: 1.3rem;
  }
  nav {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    padding: 0 0.6rem;
  }
  .nav-item {
    display: flex;
    align-items: center;
    gap: 0.6rem;
    width: 100%;
    text-align: left;
    padding: 0.7rem 0.8rem;
    border: none;
    background: transparent;
    color: #cbd5e1;
    font-size: 0.95rem;
    border-radius: 8px;
    cursor: pointer;
  }
  .nav-item:hover {
    background: #374151;
    color: #fff;
  }
  .nav-item.active {
    background: #2563eb;
    color: #fff;
  }
  .nav-icon {
    font-size: 1rem;
  }
  .content {
    flex: 1;
    background: #f5f7fa;
    overflow: hidden;
  }
</style>
