// src/DownloadView.svelte
<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';
  import { listen } from '@tauri-apps/api/event';
  import { open } from '@tauri-apps/plugin-dialog';
  import { onMount } from 'svelte';

  type TaskStatus = 'Pending' | 'Downloading' | 'Completed' | 'Failed';

  interface Task {
    id: string;
    title: string;
    bvid: string;
    page: number;
    part: string;
    mode: string;
    out_path: string;
    status: TaskStatus;
    error: string | null;
  }

  interface ProgressEvent {
    task_id: string;
    title: string;
    status: string;
    percent: number;
    downloaded: number;
    total: number;
    speed: number;
    error: string | null;
  }

  interface LoginQr {
    qr_svg: string;
    qr_key: string;
  }

  interface LoginState {
    authed: boolean;
    message: string;
  }

  // ---- 状态 ----
  let loggedIn = $state(false);
  let checkingLogin = $state(true);

  let inputUrl = $state('');
  let preferFormat = $state('1080P');
  let mode = $state('audio'); // audio | video | merge
  let outputDir = $state('');

  let tasks = $state<Task[]>([]);
  let resolving = $state(false);
  let downloading = $state(false);
  let message = $state('');

  // 登录二维码弹窗
  let showQr = $state(false);
  let qr = $state<LoginQr | null>(null);
  let qrPolling = $state<number | null>(null);

  const progressMap = $state<Record<string, ProgressEvent>>({});

  function fmtBytes(n: number): string {
    if (!n) return '0 B';
    const u = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(n) / Math.log(1024));
    return (n / Math.pow(1024, i)).toFixed(2) + ' ' + u[i];
  }

  async function pickDir() {
    try {
      const sel = await open({
        directory: true,
        multiple: false,
        title: '选择下载目录',
      });
      if (typeof sel === 'string') {
        outputDir = sel;
      }
    } catch (e) {
      message = '选择目录失败：' + String(e);
    }
  }

  async function refreshLogin() {
    checkingLogin = true;
    try {
      loggedIn = await invoke<boolean>('bili_check_login');
    } catch {
      loggedIn = false;
    } finally {
      checkingLogin = false;
    }
  }

  async function doResolve() {
    if (!loggedIn) {
      message = '请先扫码登录';
      return;
    }
    if (!inputUrl.trim()) {
      message = '请输入 BV 号或链接';
      return;
    }
    resolving = true;
    message = '';
    try {
      tasks = await invoke<Task[]>('bili_resolve', {
        input: {
          input: inputUrl.trim(),
          mode,
          preferFormat,
          outputDir: outputDir || null,
        },
      });
    } catch (e) {
      message = String(e);
      tasks = [];
    } finally {
      resolving = false;
    }
  }

  async function doDownload() {
    if (tasks.length === 0) return;
    downloading = true;
    message = '开始下载…';
    try {
      await invoke<string[]>('bili_start_download', {
        input: { outputDir: outputDir || null, concurrency: 3 },
      });
    } catch (e) {
      message = String(e);
      downloading = false;
    }
  }

  async function doLogout() {
    await invoke('bili_logout');
    loggedIn = false;
    tasks = [];
  }

  async function openQr() {
    showQr = true;
    try {
      qr = await invoke<LoginQr>('bili_login_qr');
      startPoll();
    } catch (e) {
      message = '生成二维码失败：' + String(e);
    }
  }

  function startPoll() {
    stopPoll();
    qrPolling = setInterval(async () => {
      if (!qr) return;
      try {
        const r = await invoke<LoginState>('bili_login_poll', { qrKey: qr.qr_key });
        if (r.authed) {
          loggedIn = true;
          showQr = false;
          stopPoll();
          qr = null;
          message = '登录成功';
        }
      } catch {
        /* 继续轮询 */
      }
    }, 2000) as unknown as number;
  }

  function stopPoll() {
    if (qrPolling !== null) {
      clearInterval(qrPolling);
      qrPolling = null;
    }
  }

  onMount(() => {
    refreshLogin();
    const off1 = listen<ProgressEvent>('download-progress', (e) => {
      progressMap[e.payload.task_id] = e.payload;
    });
    const off2 = listen<{ ok: boolean; failed: number }>('download-finished', (e) => {
      downloading = false;
      message = e.payload.ok ? '全部下载完成' : `下载结束，${e.payload.failed} 个失败`;
      invoke<Task[]>('bili_list_tasks')
        .then((t) => (tasks = t))
        .catch(() => {});
    });
    return async () => {
      stopPoll();
      (await off1)();
      (await off2)();
    };
  });
</script>

<div class="panel">
  {#if checkingLogin}
    <p class="hint">检查登录态…</p>
  {:else if !loggedIn}
    <div class="login-box">
      <p>当前未登录，部分功能受限。</p>
      <button onclick={openQr}>扫码登录</button>
    </div>
  {:else}
    <div class="bar">
      <span class="ok">已登录</span>
      <button class="ghost" onclick={doLogout}>登出</button>
    </div>
  {/if}

  {#if showQr && qr}
    <div class="qr">
      <p>使用 B站 APP 扫码登录</p>
      <img src={qr.qr_svg} alt="qr" width="240" height="240" />
    </div>
  {/if}

  {#if loggedIn}
    <section class="input">
      <input
        placeholder="BV 号 / 链接 / av 号 / 合集(ss) / 番剧"
        bind:value={inputUrl}
      />
      <select bind:value={mode}>
        <option value="audio">仅音频</option>
        <option value="video">仅视频</option>
        <option value="merge">音视频合并</option>
      </select>
      <select bind:value={preferFormat}>
        <option>360P</option>
        <option>720P</option>
        <option>1080P</option>
        <option>4K</option>
        <option>8K</option>
      </select>
      <button onclick={pickDir}>选择目录</button>
      <span class="dir" title={outputDir}>
        {outputDir || '默认：应用配置目录'}
      </span>
      <button onclick={doResolve} disabled={resolving}>
        {resolving ? '解析中…' : '解析'}
      </button>
      <button onclick={doDownload} disabled={downloading || tasks.length === 0}>
        {downloading ? '下载中…' : '开始下载'}
      </button>
    </section>

    {#if message}<p class="msg">{message}</p>{/if}

    {#if tasks.length}
      <ul class="tasks">
        {#each tasks as t (t.id)}
          {@const pg = progressMap[t.id]}
          <li>
            <div class="t-title">{t.title}{t.part ? ' - ' + t.part : ''}</div>
            <div class="t-meta">
              {t.mode} · {t.status}
              {#if pg}
                · {fmtBytes(pg.downloaded)}{pg.total ? ' / ' + fmtBytes(pg.total) : ''}
                · {fmtBytes(pg.speed)}/s
              {/if}
              {#if t.error}<span class="err"> · {t.error}</span>{/if}
            </div>
            <div class="progress">
              <div
                class="fill"
                style="width: {pg ? Math.round(pg.percent * 100) : (t.status === 'Completed' ? 100 : 0)}%"
              ></div>
            </div>
          </li>
        {/each}
      </ul>
    {/if}
  {/if}
</div>

<style>
  .panel {
    padding: 1.5rem;
    height: 100%;
    overflow-y: auto;
  }
  .hint {
    color: #6b7280;
  }
  .login-box {
    border: 1px dashed #cbd5e1;
    border-radius: 10px;
    padding: 1rem;
    background: #fff;
  }
  .bar {
    display: flex;
    gap: 0.5rem;
    align-items: center;
  }
  .ok {
    color: #1a7f37;
    font-weight: 600;
  }
  .input {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin: 1rem 0;
  }
  .input input,
  .input select {
    padding: 0.4rem;
  }
  .input input:first-child {
    flex: 1 1 240px;
  }
  button {
    padding: 0.4rem 0.8rem;
    cursor: pointer;
    border: none;
    border-radius: 6px;
    background: #2563eb;
    color: #fff;
    font-weight: 600;
  }
  button:disabled {
    background: #9ca3af;
    cursor: not-allowed;
  }
  button.ghost {
    background: transparent;
    color: #2563eb;
    border: 1px solid #2563eb;
  }
  .msg {
    color: #b35900;
  }
  .qr {
    margin: 1rem 0;
  }
  .tasks {
    list-style: none;
    padding: 0;
  }
  .tasks li {
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 0.6rem;
    margin-bottom: 0.6rem;
    background: #fff;
  }
  .t-title {
    font-weight: 600;
  }
  .t-meta {
    font-size: 0.8rem;
    color: #555;
    margin: 0.3rem 0;
  }
  .err {
    color: #c00;
  }
  .progress {
    height: 8px;
    background: #eee;
    border-radius: 4px;
    overflow: hidden;
  }
  .fill {
    height: 100%;
    background: #1a7f37;
    transition: width 0.2s;
  }
</style>

// src/DownloadView.vue
<script setup lang="ts">
import { onMounted, onUnmounted, reactive, ref } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import {
  QrcodeOutlined,
  LogoutOutlined,
  FolderOpenOutlined,
  SearchOutlined,
  DownloadOutlined,
} from "@ant-design/icons-vue";
import type { MenuProps } from "ant-design-vue";

type TaskStatus = "Pending" | "Downloading" | "Completed" | "Failed";

interface Task {
  id: string;
  title: string;
  bvid: string;
  page: number;
  part: string;
  mode: string;
  out_path: string;
  status: TaskStatus;
  error: string | null;
}

interface ProgressEvent {
  task_id: string;
  title: string;
  status: string;
  percent: number;
  downloaded: number;
  total: number;
  speed: number;
  error: string | null;
}

interface LoginQr {
  qr_svg: string;
  qr_key: string;
}

interface LoginState {
  authed: boolean;
  message: string;
}

// ---- 状态 ----
const loggedIn = ref(false);
const checkingLogin = ref(true);

const inputUrl = ref("");
const preferFormat = ref("1080P");
const mode = ref<"audio" | "video" | "merge">("audio");
const outputDir = ref("");

const tasks = ref<Task[]>([]);
const resolving = ref(false);
const downloading = ref(false);
const message = ref("");

// 登录二维码弹窗
const showQr = ref(false);
const qr = ref<LoginQr | null>(null);
let qrPolling: number | null = null;

const progressMap: Record<string, ProgressEvent> = reactive({});

const modeOptions: MenuProps["items"] = [
  { label: "仅音频", value: "audio" },
  { label: "仅视频", value: "video" },
  { label: "音视频合并", value: "merge" },
];
const formatOptions = ["360P", "720P", "1080P", "4K", "8K"];

function fmtBytes(n: number): string {
  if (!n) return "0 B";
  const u = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(n) / Math.log(1024));
  return (n / Math.pow(1024, i)).toFixed(2) + " " + u[i];
}

function statusColor(s: TaskStatus): string {
  switch (s) {
    case "Completed":
      return "success";
    case "Failed":
      return "error";
    case "Downloading":
      return "processing";
    default:
      return "default";
  }
}

async function pickDir() {
  try {
    const sel = await open({
      directory: true,
      multiple: false,
      title: "选择下载目录",
    });
    if (typeof sel === "string") {
      outputDir.value = sel;
    }
  } catch (e) {
    message.value = "选择目录失败：" + String(e);
  }
}

async function refreshLogin() {
  checkingLogin.value = true;
  try {
    loggedIn.value = await invoke<boolean>("bili_check_login");
  } catch {
    loggedIn.value = false;
  } finally {
    checkingLogin.value = false;
  }
}

async function doResolve() {
  if (!loggedIn.value) {
    message.value = "请先扫码登录";
    return;
  }
  if (!inputUrl.value.trim()) {
    message.value = "请输入 BV 号或链接";
    return;
  }
  resolving.value = true;
  message.value = "";
  try {
    tasks.value = await invoke<Task[]>("bili_resolve", {
      input: {
        input: inputUrl.value.trim(),
        mode: mode.value,
        preferFormat: preferFormat.value,
        outputDir: outputDir.value || null,
      },
    });
  } catch (e) {
    message.value = String(e);
    tasks.value = [];
  } finally {
    resolving.value = false;
  }
}

async function doDownload() {
  if (tasks.value.length === 0) return;
  downloading.value = true;
  message.value = "开始下载…";
  try {
    await invoke<string[]>("bili_start_download", {
      input: { outputDir: outputDir.value || null, concurrency: 3 },
    });
  } catch (e) {
    message.value = String(e);
    downloading.value = false;
  }
}

async function doLogout() {
  await invoke("bili_logout");
  loggedIn.value = false;
  tasks.value = [];
}

async function openQr() {
  showQr.value = true;
  try {
    qr.value = await invoke<LoginQr>("bili_login_qr");
    startPoll();
  } catch (e) {
    message.value = "生成二维码失败：" + String(e);
  }
}

function startPoll() {
  stopPoll();
  qrPolling = setInterval(async () => {
    if (!qr.value) return;
    try {
      const r = await invoke<LoginState>("bili_login_poll", {
        qrKey: qr.value.qr_key,
      });
      if (r.authed) {
        loggedIn.value = true;
        showQr.value = false;
        stopPoll();
        qr.value = null;
        message.value = "登录成功";
      }
    } catch {
      /* 继续轮询 */
    }
  }, 2000) as unknown as number;
}

function stopPoll() {
  if (qrPolling !== null) {
    clearInterval(qrPolling);
    qrPolling = null;
  }
}

let off1: UnlistenFn | null = null;
let off2: UnlistenFn | null = null;

onMounted(async () => {
  await refreshLogin();
  off1 = await listen<ProgressEvent>("download-progress", (e) => {
    progressMap[e.payload.task_id] = e.payload;
  });
  off2 = await listen<{ ok: boolean; failed: number }>(
    "download-finished",
    (e) => {
      downloading.value = false;
      message.value = e.payload.ok
        ? "全部下载完成"
        : `下载结束，${e.payload.failed} 个失败`;
      invoke<Task[]>("bili_list_tasks")
        .then((t) => (tasks.value = t))
        .catch(() => {});
    }
  );
});

onUnmounted(() => {
  stopPoll();
  off1?.();
  off2?.();
});
</script>

<template>
  <div class="panel">
    <a-card :bordered="false" class="top-card">
      <a-space v-if="checkingLogin">
        <a-spin size="small" /> 检查登录态…
      </a-space>
      <a-alert
        v-else-if="!loggedIn"
        type="warning"
        show-icon
        message="当前未登录，部分功能受限。"
      >
        <template #action>
          <a-button type="primary" size="small" @click="openQr">
            <template #icon><QrcodeOutlined /></template>
            扫码登录
          </a-button>
        </template>
      </a-alert>
      <a-space v-else>
        <a-badge status="success" text="已登录" />
        <a-button size="small" @click="doLogout">
          <template #icon><LogoutOutlined /></template>
          登出
        </a-button>
      </a-space>
    </a-card>

    <a-modal
      v-model:open="showQr"
      title="扫码登录"
      :footer="null"
      centered
    >
      <a-spin :spinning="!qr" tip="正在生成登录二维码…">
        <div class="qr-wrap" v-if="qr">
          <p>使用 B站 APP 扫码登录</p>
          <img :src="qr.qr_svg" alt="qr" width="240" height="240" />
        </div>
      </a-spin>
    </a-modal>

    <a-card v-if="loggedIn" title="B站下载" :bordered="false" class="main-card">
      <a-form layout="vertical">
        <a-form-item label="视频地址">
          <a-input
            v-model:value="inputUrl"
            placeholder="BV 号 / 链接 / av 号 / 合集(ss) / 番剧"
            allow-clear
          />
        </a-form-item>
        <a-row :gutter="12">
          <a-col :span="8">
            <a-form-item label="下载模式">
              <a-select v-model:value="mode" :options="modeOptions" />
            </a-form-item>
          </a-col>
          <a-col :span="8">
            <a-form-item label="首选清晰度">
              <a-select v-model:value="preferFormat" :options="formatOptions.map((f) => ({ label: f, value: f }))" />
            </a-form-item>
          </a-col>
          <a-col :span="8">
            <a-form-item label="输出目录">
              <a-space>
                <a-button @click="pickDir">
                  <template #icon><FolderOpenOutlined /></template>
                  选择目录
                </a-button>
                <a-typography-text type="secondary" :ellipsis="{ tooltip: outputDir }">
                  {{ outputDir || "默认：应用配置目录" }}
                </a-typography-text>
              </a-space>
            </a-form-item>
          </a-col>
        </a-row>
        <a-space>
          <a-button type="primary" :loading="resolving" @click="doResolve">
            <template #icon><SearchOutlined /></template>
            {{ resolving ? "解析中…" : "解析" }}
          </a-button>
          <a-button
            type="primary"
            :loading="downloading"
            :disabled="tasks.length === 0"
            @click="doDownload"
          >
            <template #icon><DownloadOutlined /></template>
            {{ downloading ? "下载中…" : "开始下载" }}
          </a-button>
        </a-space>
      </a-form>

      <a-alert
        v-if="message"
        class="msg"
        type="info"
        show-icon
        :message="message"
      />

      <a-list
        v-if="tasks.length"
        class="task-list"
        item-layout="horizontal"
        :data-source="tasks"
      >
        <template #renderItem="{ item }">
          <a-list-item>
            <a-card size="small" :bordered="false" class="task-card">
              <div class="t-title">
                {{ item.title
                }}{{ item.part ? " - " + item.part : "" }}
              </div>
              <div class="t-meta">
                <a-tag :color="statusColor(item.status)">{{ item.status }}</a-tag>
                <a-tag>{{ item.mode }}</a-tag>
                <template v-if="progressMap[item.id]">
                  {{ fmtBytes(progressMap[item.id].downloaded)
                  }}<template v-if="progressMap[item.id].total">
                    / {{ fmtBytes(progressMap[item.id].total) }}</template>
                  · {{ fmtBytes(progressMap[item.id].speed) }}/s
                </template>
                <span v-if="item.error" class="err"> · {{ item.error }}</span>
              </div>
              <a-progress
                :percent="
                  progressMap[item.id]
                    ? Math.round(progressMap[item.id].percent * 100)
                    : item.status === 'Completed'
                    ? 100
                    : 0
                "
                :status="item.status === 'Failed' ? 'exception' : undefined"
                size="small"
              />
            </a-card>
          </a-list-item>
        </template>
      </a-list>
    </a-card>
  </div>
</template>

<style scoped>
.panel {
  padding: 1.5rem;
  height: 100%;
  overflow-y: auto;
}
.top-card {
  margin-bottom: 1rem;
}
.main-card {
  background: #fff;
}
.qr-wrap {
  text-align: center;
}
.msg {
  margin: 1rem 0;
}
.task-list {
  margin-top: 1rem;
}
.task-card {
  width: 100%;
  background: #fafafa;
}
.t-title {
  font-weight: 600;
}
.t-meta {
  font-size: 0.8rem;
  color: #555;
  margin: 0.3rem 0;
}
.err {
  color: #c00;
}
</style>
