// src/RecognizerView.vue
<script setup lang="ts">
import { ref } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import {
  AudioOutlined,
  SearchOutlined,
} from "@ant-design/icons-vue";

interface SongInfo {
  title: string;
  artist: string;
  album: string | null;
  album_date: string | null;
  confidence: number;
}

const filePath = ref("");
const result = ref<SongInfo | null>(null);
const message = ref("");
const identifying = ref(false);

async function pickFile() {
  try {
    const sel = await open({
      multiple: false,
      title: "选择音频文件",
      filters: [
        {
          name: "音频",
          extensions: ["mp3", "flac", "m4a", "wav", "ogg", "opus", "aac"],
        },
      ],
    });
    if (typeof sel === "string") {
      filePath.value = sel;
      result.value = null;
      message.value = "";
    }
  } catch (e) {
    message.value = "选择文件失败：" + String(e);
  }
}

async function doIdentify() {
  if (!filePath.value) {
    message.value = "请先选择音频文件";
    return;
  }
  identifying.value = true;
  message.value = "";
  result.value = null;
  try {
    const r = await invoke<SongInfo>("identify", { path: filePath.value });
    result.value = r;
  } catch (e) {
    message.value = "识别失败：" + String(e);
  } finally {
    identifying.value = false;
  }
}
</script>

<template>
  <div class="panel">
    <a-card title="音频识别" :bordered="false" class="main-card">
      <p class="desc">
        通过音频指纹（Chromaprint）匹配 AcoustID，识别歌曲的标题、艺术家与专辑信息。
      </p>

      <a-space wrap class="input">
        <a-button @click="pickFile">
          <template #icon><AudioOutlined /></template>
          选择音频文件
        </a-button>
        <a-typography-text
          v-if="filePath"
          type="secondary"
          :ellipsis="{ tooltip: filePath }"
          style="max-width: 320px"
        >
          {{ filePath }}
        </a-typography-text>
        <a-typography-text v-else type="secondary">未选择文件</a-typography-text>
        <a-button
          type="primary"
          :loading="identifying"
          :disabled="!filePath"
          @click="doIdentify"
        >
          <template #icon><SearchOutlined /></template>
          {{ identifying ? "识别中…" : "开始识别" }}
        </a-button>
      </a-space>

      <a-alert
        v-if="message"
        class="msg"
        type="warning"
        show-icon
        :message="message"
      />

      <a-spin :spinning="identifying" tip="正在计算音频指纹并查询 AcoustID…">
        <a-card v-if="result" size="small" class="result-card" :bordered="false">
          <a-descriptions :column="1" bordered size="small">
            <a-descriptions-item label="标题">
              {{ result.title }}
            </a-descriptions-item>
            <a-descriptions-item label="艺术家">
              {{ result.artist }}
            </a-descriptions-item>
            <a-descriptions-item label="专辑">
              {{ result.album ?? "—" }}
            </a-descriptions-item>
            <a-descriptions-item label="发行日期">
              {{ result.album_date ?? "—" }}
            </a-descriptions-item>
            <a-descriptions-item label="置信度">
              {{ result.confidence.toFixed(1) }}%
            </a-descriptions-item>
          </a-descriptions>
        </a-card>
        <div v-else-if="!identifying" class="placeholder">
          选择音频文件并点击「开始识别」以查看结果
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<style scoped>
.panel {
  padding: 1.5rem;
  height: 100%;
  overflow-y: auto;
}
.main-card {
  background: #fff;
}
.desc {
  color: #6b7280;
  font-size: 0.9rem;
}
.input {
  margin: 1rem 0;
}
.msg {
  margin: 1rem 0;
}
.result-card {
  margin-top: 1rem;
  background: #fafafa;
}
.placeholder {
  margin-top: 1rem;
  padding: 2rem;
  text-align: center;
  color: #9ca3af;
  background: #fafafa;
  border: 1px dashed #e2e8f0;
  border-radius: 8px;
}
</style>

// src/RecognizerView.svelte
<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';
  import { open } from '@tauri-apps/plugin-dialog';

  interface SongInfo {
    title: string;
    artist: string;
    album: string | null;
    album_date: string | null;
    confidence: number;
  }

  let filePath = $state('');
  let result = $state<SongInfo | null>(null);
  let message = $state('');
  let identifying = $state(false);

  async function pickFile() {
    try {
      const sel = await open({
        multiple: false,
        title: '选择音频文件',
        filters: [
          { name: '音频', extensions: ['mp3', 'flac', 'm4a', 'wav', 'ogg', 'opus', 'aac'] },
        ],
      });
      if (typeof sel === 'string') {
        filePath = sel;
        result = null;
        message = '';
      }
    } catch (e) {
      message = '选择文件失败：' + String(e);
    }
  }

  async function doIdentify() {
    if (!filePath) {
      message = '请先选择音频文件';
      return;
    }
    identifying = true;
    message = '';
    result = null;
    try {
      const r = await invoke<SongInfo>('identify', { path: filePath });
      result = r;
    } catch (e) {
      message = '识别失败：' + String(e);
    } finally {
      identifying = false;
    }
  }
</script>

<div class="panel">
  <h2>音频识别</h2>
  <p class="desc">通过音频指纹（Chromaprint）匹配 AcoustID，识别歌曲的标题、艺术家与专辑信息。</p>

  <section class="input">
    <button onclick={pickFile}>选择音频文件</button>
    <span class="file" title={filePath}>{filePath || '未选择文件'}</span>
    <button onclick={doIdentify} disabled={identifying || !filePath}>
      {identifying ? '识别中…' : '开始识别'}
    </button>
  </section>

  {#if message}<p class="msg">{message}</p>{/if}

  {#if result}
    <div class="result">
      <div class="row">
        <span class="label">标题</span>
        <span class="value">{result.title}</span>
      </div>
      <div class="row">
        <span class="label">艺术家</span>
        <span class="value">{result.artist}</span>
      </div>
      <div class="row">
        <span class="label">专辑</span>
        <span class="value">{result.album ?? '—'}</span>
      </div>
      <div class="row">
        <span class="label">发行日期</span>
        <span class="value">{result.album_date ?? '—'}</span>
      </div>
      <div class="row">
        <span class="label">置信度</span>
        <span class="value">{result.confidence.toFixed(1)}%</span>
      </div>
    </div>
  {/if}
</div>

<style>
  .panel {
    padding: 1.5rem;
    height: 100%;
    overflow-y: auto;
  }
  h2 {
    margin-top: 0;
  }
  .desc {
    color: #6b7280;
    font-size: 0.9rem;
  }
  .input {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    align-items: center;
    margin: 1rem 0;
  }
  button {
    padding: 0.4rem 0.8rem;
    cursor: pointer;
    border: none;
    border-radius: 6px;
    background: #2563eb;
    color: #fff;
    font-weight: 600;
  }
  button:disabled {
    background: #9ca3af;
    cursor: not-allowed;
  }
  .file {
    max-width: 320px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    color: #555;
    font-size: 0.85rem;
  }
  .msg {
    color: #b35900;
  }
  .result {
    margin-top: 1rem;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
    background: #fff;
    padding: 1rem;
  }
  .row {
    display: flex;
    padding: 0.4rem 0;
    border-bottom: 1px solid #f1f5f9;
  }
  .row:last-child {
    border-bottom: none;
  }
  .label {
    width: 80px;
    color: #6b7280;
    font-size: 0.9rem;
  }
  .value {
    font-weight: 600;
  }
</style>
